export type KeyDef = {
  code: string;
  label: string;
  xOffset?: number;
  width?: number;
  height?: number;
};

export const usLayout: KeyDef[][] = [
  [
    { code: 'Escape', label: 'Esc' },
    { code: 'F1', label: 'F1', xOffset: 1 },
    { code: 'F2', label: 'F2' },
    { code: 'F3', label: 'F3' },
    { code: 'F4', label: 'F4' },
    { code: 'F5', label: 'F5', xOffset: 0.33 },
    { code: 'F6', label: 'F6' },
    { code: 'F7', label: 'F7' },
    { code: 'F8', label: 'F8' },
    { code: 'F9', label: 'F9', xOffset: 0.33 },
    { code: 'F10', label: 'F10' },
    { code: 'F11', label: 'F11' },
    { code: 'F12', label: 'F12' },
    { code: 'PrintScreen', label: 'PrtSc', xOffset: 0.54 },
    { code: 'ScrollLock', label: 'Scroll' },
    { code: 'Pause', label: 'Pause' },
  ],
  [
    { code: 'BackQuote', label: '`' },
    { code: 'Num1', label: '1' },
    { code: 'Num2', label: '2' },
    { code: 'Num3', label: '3' },
    { code: 'Num4', label: '4' },
    { code: 'Num5', label: '5' },
    { code: 'Num6', label: '6' },
    { code: 'Num7', label: '7' },
    { code: 'Num8', label: '8' },
    { code: 'Num9', label: '9' },
    { code: 'Num0', label: '0' },
    { code: 'Minus', label: '-' },
    { code: 'Equal', label: '=' },
    { code: 'Backspace', label: 'BackSpace', width: 2 },
    { code: 'Insert', label: 'Insert', xOffset: 1.2 },
    { code: 'Home', label: 'Home' },
    { code: 'PageUp', label: 'PageUp' },
    { code: 'NumLock', label: 'NumLock', xOffset: 0.2 },
    { code: 'KpDivide', label: '/' },
    { code: 'KpMultiply', label: '*' },
    { code: 'KpMinus', label: '-' },
  ],
  [
    { code: 'Tab', label: 'Tab', width: 1.5 },
    { code: 'KeyQ', label: 'Q', xOffset: 0.5 },
    { code: 'KeyW', label: 'W' },
    { code: 'KeyE', label: 'E' },
    { code: 'KeyR', label: 'R' },
    { code: 'KeyT', label: 'T' },
    { code: 'KeyY', label: 'Y' },
    { code: 'KeyU', label: 'U' },
    { code: 'KeyI', label: 'I' },
    { code: 'KeyO', label: 'O' },
    { code: 'KeyP', label: 'P' },
    { code: 'LeftBracket', label: '[' },
    { code: 'RightBracket', label: ']' },
    { code: 'BackSlash', label: '\\', width: 1.5 },
    { code: 'Delete', label: 'Delete', xOffset: 0.7 },
    { code: 'End', label: 'End' },
    { code: 'PageDown', label: 'PageDown' },
    { code: 'Kp7', label: '7', xOffset: 0.2 },
    { code: 'Kp8', label: '8' },
    { code: 'Kp9', label: '9' },
    { code: 'KpPlus', label: '+', height: 2 },
  ],
  [
    { code: 'CapsLock', label: 'CapsLock', width: 1.7 },
    { code: 'KeyA', label: 'A', xOffset: 0.7 },
    { code: 'KeyS', label: 'S' },
    { code: 'KeyD', label: 'D' },
    { code: 'KeyF', label: 'F' },
    { code: 'KeyG', label: 'G' },
    { code: 'KeyH', label: 'H' },
    { code: 'KeyJ', label: 'J' },
    { code: 'KeyK', label: 'K' },
    { code: 'KeyL', label: 'L' },
    { code: 'SemiColon', label: ';' },
    { code: 'Quote', label: "'" },
    { code: 'Return', label: 'Enter', width: 2.3 },
    { code: '', label: '' },
    { code: '', label: '' },
    { code: '', label: '' },
    { code: 'Kp4', label: '4', xOffset: 1.7 },
    { code: 'Kp5', label: '5' },
    { code: 'Kp6', label: '6' },
  ],
  [
    { code: 'ShiftLeft', label: 'Shift', width: 2.2 },
    { code: 'KeyZ', label: 'Z', xOffset: 1.2 },
    { code: 'KeyX', label: 'X' },
    { code: 'KeyC', label: 'C' },
    { code: 'KeyV', label: 'V' },
    { code: 'KeyB', label: 'B' },
    { code: 'KeyN', label: 'N' },
    { code: 'KeyM', label: 'M' },
    { code: 'Comma', label: ',' },
    { code: 'Dot', label: '.' },
    { code: 'Slash', label: '/' },
    { code: 'ShiftRight', label: 'Shift', width: 2.8 },
    { code: '', label: '' },
    { code: 'UpArrow', label: '↑', xOffset: 2 },
    { code: '', label: '' },
    { code: 'Kp1', label: '1', xOffset: 0.2 },
    { code: 'Kp2', label: '2' },
    { code: 'Kp3', label: '3' },
    { code: 'Return', label: 'Enter', height: 2 },
  ],
  [
    { code: 'ControlLeft', label: 'Ctrl', width: 1.5 },
    { code: 'MetaLeft', label: 'Win/Opt', width: 1.2, xOffset: 0.5 },
    { code: 'Alt', label: 'Alt/Cmd', width: 1.2, xOffset: 0.2 },
    { code: 'Space', label: 'Space', width: 5.9, xOffset: 0.2 },
    { code: 'AltGr', label: 'Alt/Cmd', width: 1.2, xOffset: 4.9 },
    { code: 'MetaRight', label: 'Win/Opt', width: 1.2, xOffset: 0.2 },
    { code: 'Apps', label: 'Menu', width: 1.2, xOffset: 0.2 },
    { code: 'ControlRight', label: 'Ctrl', width: 1.6, xOffset: 0.2 },
    { code: 'LeftArrow', label: '←', xOffset: 0.8 },
    { code: 'DownArrow', label: '↓' },
    { code: 'RightArrow', label: '→' },
    { code: 'Kp0', label: '0', width: 2, xOffset: 0.2 },
    { code: 'KpDecimal', label: '.', xOffset: 1 },
  ],
];

export const jpLayout: KeyDef[][] = [
  [
    { code: 'Escape', label: 'Esc' },
    { code: 'F1', label: 'F1', xOffset: 1 },
    { code: 'F2', label: 'F2' },
    { code: 'F3', label: 'F3' },
    { code: 'F4', label: 'F4' },
    { code: 'F5', label: 'F5', xOffset: 0.33 },
    { code: 'F6', label: 'F6' },
    { code: 'F7', label: 'F7' },
    { code: 'F8', label: 'F8' },
    { code: 'F9', label: 'F9', xOffset: 0.33 },
    { code: 'F10', label: 'F10' },
    { code: 'F11', label: 'F11' },
    { code: 'F12', label: 'F12' },
    { code: 'PrintScreen', label: 'PrtSc', xOffset: 0.54 },
    { code: 'ScrollLock', label: 'Scroll' },
    { code: 'Pause', label: 'Pause' },
  ],
  [
    { code: 'Unknown(243)', label: '半角', width: 0.5 },
    { code: 'Unknown(244)', label: '全角', width: 0.5, xOffset: -0.5 },
    { code: 'Num1', label: '1', xOffset: -0.5 },
    { code: 'Num2', label: '2' },
    { code: 'Num3', label: '3' },
    { code: 'Num4', label: '4' },
    { code: 'Num5', label: '5' },
    { code: 'Num6', label: '6' },
    { code: 'Num7', label: '7' },
    { code: 'Num8', label: '8' },
    { code: 'Num9', label: '9' },
    { code: 'Num0', label: '0' },
    { code: 'Minus', label: '-' },
    { code: 'Quote', label: '^' },
    { code: 'BackSlash', label: '¥' },
    { code: 'Backspace', label: 'BackSpace' },
    { code: 'Insert', label: 'Insert', xOffset: 0.2 },
    { code: 'Home', label: 'Home' },
    { code: 'PageUp', label: 'PageUp' },
    { code: 'NumLock', label: 'NumLock', xOffset: 0.2 },
    { code: 'KpDivide', label: '/' },
    { code: 'KpMultiply', label: '*' },
    { code: 'KpMinus', label: '-' },
  ],
  [
    { code: 'Tab', label: 'Tab', width: 1.5 },
    { code: 'KeyQ', label: 'Q', xOffset: 0.5 },
    { code: 'KeyW', label: 'W' },
    { code: 'KeyE', label: 'E' },
    { code: 'KeyR', label: 'R' },
    { code: 'KeyT', label: 'T' },
    { code: 'KeyY', label: 'Y' },
    { code: 'KeyU', label: 'U' },
    { code: 'KeyI', label: 'I' },
    { code: 'KeyO', label: 'O' },
    { code: 'KeyP', label: 'P' },
    { code: 'BackQuote', label: '@' },
    { code: 'LeftBracket', label: '[' },
    { code: 'Return', label: 'Enter', width: 1.5 },
    { code: 'Delete', label: 'Delete', xOffset: 0.7 },
    { code: 'End', label: 'End' },
    { code: 'PageDown', label: 'PageDown' },
    { code: 'Kp7', label: '7', xOffset: 0.2 },
    { code: 'Kp8', label: '8' },
    { code: 'Kp9', label: '9' },
    { code: 'KpPlus', label: '+', height: 2 },
  ],
  [
    { code: 'CapsLock', label: 'CapsLock', width: 1.7 },
    { code: 'KeyA', label: 'A', xOffset: 0.7 },
    { code: 'KeyS', label: 'S' },
    { code: 'KeyD', label: 'D' },
    { code: 'KeyF', label: 'F' },
    { code: 'KeyG', label: 'G' },
    { code: 'KeyH', label: 'H' },
    { code: 'KeyJ', label: 'J' },
    { code: 'KeyK', label: 'K' },
    { code: 'KeyL', label: 'L' },
    { code: 'Equal', label: ';' },
    { code: 'Semicolon', label: ':' },
    { code: 'RightBracket', label: ']' },
    { code: '', label: '' },
    { code: '', label: '' },
    { code: '', label: '' },
    { code: 'Kp4', label: '4', xOffset: 1.7 },
    { code: 'Kp5', label: '5' },
    { code: 'Kp6', label: '6' },
  ],
  [
    { code: 'ShiftLeft', label: 'Shift', width: 2.2 },
    { code: 'KeyZ', label: 'Z', xOffset: 1.2 },
    { code: 'KeyX', label: 'X' },
    { code: 'KeyC', label: 'C' },
    { code: 'KeyV', label: 'V' },
    { code: 'KeyB', label: 'B' },
    { code: 'KeyN', label: 'N' },
    { code: 'KeyM', label: 'M' },
    { code: 'Comma', label: ',' },
    { code: 'Dot', label: '.' },
    { code: 'Slash', label: '/' },
    { code: 'IntlBackslash', label: '\\' },
    { code: 'ShiftRight', label: 'Shift', width: 1.8 },
    { code: '', label: '' },
    { code: 'UpArrow', label: '↑', xOffset: 1 },
    { code: '', label: '' },
    { code: 'Kp1', label: '1', xOffset: 0.2 },
    { code: 'Kp2', label: '2' },
    { code: 'Kp3', label: '3' },
    { code: 'Return', label: 'Enter', height: 2 },
  ],
  [
    { code: 'ControlLeft', label: 'Ctrl', width: 1.7 },
    { code: 'MetaLeft', label: 'Win/Opt', xOffset: 0.7 },
    { code: 'Alt', label: 'Alt/Cmd' },
    { code: 'Lang1', label: '無変換' },
    { code: 'Space', label: 'Space', width: 3 },
    { code: 'Lang2', label: '変換', xOffset: 2 },
    { code: 'KanaMode', label: 'カナ/かな' },
    { code: 'AltGr', label: 'Alt/Cmd' },
    { code: 'MetaRight', label: 'Win/Opt' },
    { code: 'Apps', label: 'Menu' },
    { code: 'ControlRight', label: 'Ctrl', width: 2.3 },
    { code: 'LeftArrow', label: '←', xOffset: 1.5 },
    { code: 'DownArrow', label: '↓' },
    { code: 'RightArrow', label: '→' },
    { code: 'Kp0', label: '0', width: 2, xOffset: 0.2 },
    { code: 'KpDecimal', label: '.', xOffset: 1 },
  ],
];

export const formatKeyCode = (keyCode: string) => {
  // rdevのキーコードを日本語表示に変換
  const keyMap: { [key: string]: string } = {
    KeyA: 'A',
    KeyB: 'B',
    KeyC: 'C',
    KeyD: 'D',
    KeyE: 'E',
    KeyF: 'F',
    KeyG: 'G',
    KeyH: 'H',
    KeyI: 'I',
    KeyJ: 'J',
    KeyK: 'K',
    KeyL: 'L',
    KeyM: 'M',
    KeyN: 'N',
    KeyO: 'O',
    KeyP: 'P',
    KeyQ: 'Q',
    KeyR: 'R',
    KeyS: 'S',
    KeyT: 'T',
    KeyU: 'U',
    KeyV: 'V',
    KeyW: 'W',
    KeyX: 'X',
    KeyY: 'Y',
    KeyZ: 'Z',
    Backspace: 'BackSpace',
    Return: 'Enter',
    Escape: 'Esc',
    'Unknown(244)': '全角',
    'Unknown(243)': '半角',
    LeftArrow: '←',
    RightArrow: '→',
    UpArrow: '↑',
    DownArrow: '↓',
    KpDivide: 'KeyPad /',
    KpMultiply: 'KeyPad *',
    KpMinus: 'KeyPad -',
    KpPlus: 'KeyPad +',
    KpDecimal: 'KeyPad .',
    KpEqual: 'KeyPad =',
    Kp0: 'KeyPad 0',
    Kp1: 'KeyPad 1',
    Kp2: 'KeyPad 2',
    Kp3: 'KeyPad 3',
    Kp4: 'KeyPad 4',
    Kp5: 'KeyPad 5',
    Kp6: 'KeyPad 6',
    Kp7: 'KeyPad 7',
    Kp8: 'KeyPad 8',
    Kp9: 'KeyPad 9',
    Num0: 'Num 0',
    Num1: 'Num 1',
    Num2: 'Num 2',
    Num3: 'Num 3',
    Num4: 'Num 4',
    Num5: 'Num 5',
    Num6: 'Num 6',
    Num7: 'Num 7',
    Num8: 'Num 8',
    Num9: 'Num 9',
  };
  return keyMap[keyCode] || keyCode;
};
